services:
  - type: web
    name: pet-adoption
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn pet_adoption.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DATABASE_URL
        fromDatabase:
          name: pet-adoption-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False